### PR TITLE
Add webpage highlights in resources, tweak style

### PR DESCRIPTION
**Pull request by ftessier**
@marmetl I don't know if you want to preserve this `Webpage highlights` section at the bottom of the resources page. I removed the items related to old newsletter announcements and acg back online in 2018. Compare with bottom of [original page.](http://cosmology.info/resources/index.html) Perhaps add these items as resources and remove the `highlights` section? The intent of this section and its difference from `Resources` is not clear to me. I presume these highlights going forward would be announced under Discussions?

### CODE REVIEW

**Review by marmetl — APPROVED** [review]

**Comment by marmetl** [comment]
Now he options are: "Merge", "Rebase and Merge", and a new one "Squash and Merge"... More to learn!

**Comment by ftessier** [comment]
Indeed. This becomes clearer as you start thinking in terms of commits and as you become more comfortable moving commits around (took me a good while!). Briefly:

- **Merge:** creates a "merge" commit, that is, the topology of the side branch is preserved. This is useful when you want to keep the history of the commits on the pr branch, for example to preserve the individual steps in a large pr. When there is only one commit in the pr, this is pretty useless, as it just creates "noise" in the commit history (called merge _bubbles_).

- **Rebase and merge:** takes all the pr commits and _replays_ them on top of the target branch, as if they had been committed directly there. This helps keep the commit history linear. When there is a single commit in the pr, this is the best option, since it just adds the commit to `main`, without creating a useless merge bubble.

- **Squash and merge:** This takes all the commits in the pr branch and squashes (combines) them into a single commit. It then _replays_ that squashed commit on top of the target branch (as in rebase). This is useful when you have many commits that are irrelevant to keep. For example, you may have changed the text, and added a bunch of additional extra commits to fix typos, tweak style, undo some changes, etc. If in the end you only want this to be a single commit in the history, you can squash everything together and add it to `main`.

It is a lot to absorb in I know! But you seem to be learning this really fast! 👍🏻 The key is understanding that a repo is just a big bag of individual commit objects link together, and that you can move these objects around, link them in a different order, edit them, squash them, etc.

**Comment by marmetl** [comment]
Makes sense.  (And ChatGPT tells me that "pr" in "pr branch" means 'pull request' ;-)

**Comment by marmetl** [comment]
> @marmetl I don't know if you want to preserve this `Webpage highlights` section at the bottom of the resources page.
  The main [ACG webpage](https://cosmology.info/) has a column on the right with 'recent' highlights.  When new highlights are added, old ones were moved there.  This could go on its own page. (to be decided later)

  However, is there a way to add a side column to the GitHub ACG website?  Something like a 'list of contents' or 'navigation' so the visitor would know where to go?

**Comment by marmetl** [comment]
The [GitHub generated ACG webpage](https://a-cosmology-group.github.io/acg/) displays "View on GitHub" on the top-right corner.
 Is there a way to get rid of that, or is that the publicity we must display for a free organization?

**Comment by ftessier** [comment]
Currently, the webpage is generated with one of the standard default [Jekyll themes](https://pages.github.com/themes/) called `Slate`. As far as I know, this is entirely configurable, and you can pretty much deploy any html you want. Unfortunately, I don't know [Jekyll](https://jekyllrb.com/), but I will look into it as time allows. You don't have to show the `github` button.

**Comment by ftessier** [comment]
Note that you don't need to use Jekyll at all, as far as I know. Jekyll is convenient and geared towards building a lightweight blog sites. But you can just as well upload a static site generated offline with any website build tool. Again, I don't know enough to provide more insight at this point.

**Pull request merged**
