### PR TITLE
Change colour scheme purple to 395 nm H-K line

### PR DESCRIPTION
**Pull request by ftessier**

### CODE REVIEW

**Comment by marmetl** [comment]
That will undo the changes I made to other files... Is there a way to accept the merge for acg.scss but leave the other files unchanged?

**Comment by ftessier** [comment]
There is only one file changed under `Files changed`, I don't understand what you mean by other files.

**Comment by marmetl** [comment]
Somehow when I clicked on ["force-pushed"](https://github.com/a-cosmology-group/acg/compare/680b1cfc5f1561b2fb971200ce297c1ea8767c56..281085877d126df0a20e9e53219de1bb8a9df450) above
(@[ftessier](https://github.com/ftessier) ftessier [force-pushed](https://github.com/a-cosmology-group/acg/compare/680b1cfc5f1561b2fb971200ce297c1ea8767c56..281085877d126df0a20e9e53219de1bb8a9df450) the ftessier-395nm branch from[ 6](https://github.com/a-cosmology-group/acg/commit/680b1cfc5f1561b2fb971200ce297c1ea8767c56))
 it leads me to some other files being changed.

But that's ok, it's the changes I made that were updated in your branch...

Never mind, I am the only one who checks all the steps and surprised each time that GitHub is a robust system ;-)

**Review by marmetl — APPROVED** [review]

**Comment by marmetl** [comment]
It worked ! 🥳 Looks dark on my monitor, looks good on my phone.

**Comment by ftessier** [comment]
All right, looks dark on work monitor, but nice on home monitor.

**Pull request merged**
