### PR TITLE
Change colour scheme purple to 395 nm H-K line

### PR DESCRIPTION
**Pull request by ftessier**
Here is an attempt to change the purple colour to #8000a1, but I have no idea how to test this other than to merge it in the main branch. Not sure this will work at all! Any tips on how to test this on the side is welcome!

MAYOR: Merge at your own risk 😄

### CODE REVIEW

**Review by marmetl — APPROVED** [review]
You can test this separately on your computer but you need to install Jekyll, `just-the-docs` and perhaps other stuff...

Since most changes to the website are not critical, and we get two visitors per day, I opted for the second option = test it live!
 (`color_schemes` seems to be for 'light' or 'dark', but I haven't read the instructions carefully... so there is a risk the website might become like "dark matter" 😄 )

**Comment by marmetl** [comment]
No effect...
For your tests @ftessier don't hesitate to merge without my approval, otherwise it will take forever to debug this!

**Comment by ftessier** [comment]
Ok, thanks for the freedom. I will try to find a way to test offline though, more efficient! Will resort to live testing if I cannot figure it out.

**Comment by marmetl** [comment]
What does `!default` do?  It's not used in their [example here](https://just-the-docs.com/docs/customization/#example-1)

**Comment by ftessier** [comment]
I think you figured it out, the `!default` keyword in Sass essentially means "assign this variable _unless it has already been set. From the [docs](https://sass-lang.com/documentation/variables/#default-values):

> To make this possible, Sass provides the `!default` flag. This assigns a value to a variable only if that variable isn’t defined or its value is null. Otherwise, the existing value will be used.

**Comment by ftessier** [comment]
Bingo, removing `!default` works. But don't merge just yet, I will tune the colour saturation.

**Comment by ftessier** [comment]
I played with saturation and lightness, to get something decent. Unfortunately, the 395 nm purple looks a lot like the default _followed_ link colour of old (90s):

image

**Pull request merged**
